modified integration tests

diff --git a/.github/workflows/integrationworkflow.yml b/.github/workflows/integrationworkflow.yml
--- a/.github/workflows/integrationworkflow.yml
+++ b/.github/workflows/integrationworkflow.yml
@@ -63,5 +63,11 @@ jobs:
         run: npm install
 
       - name: Run tests
-        run: npm run test:integration
+        run: |
+          npm run test:integration
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Integration test failed."
+            exit  $exit_code
+          fi
           
